import "./globals.css";
import { Shippori_Mincho } from "next/font/google";
import ResponsiveAppBar from "./components/MUIheader/MUIheader";
import Footer from "./components/footer/Footer";

const ShipporiMincho = Shippori_Mincho({ weight: "400", subsets: ["latin"] });
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ja">
            <body style={{ backgroundColor: "#161616" }}>
                <ResponsiveAppBar />
                <main style={{ minHeight: "88vh" }}>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
