import "./globals.css";
import Head from 'next/head';

import { Shippori_Mincho } from "next/font/google";

const ShipporiMincho = Shippori_Mincho({weight:"400",subsets:["latin"]})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
        <Head>
        <style>
        </style>
      </Head>
      <body>{children}</body>
    </html>
  );
}
